name: Github sanity scanner

on:
    pull_request:
        branches: [master]

permissions:
    contents: read

jobs:
    github-sanity-scan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
            - name: Github sanity scanner
              uses: outscale/github-sanity-scan@main
              with:
                  no-pull-request-target: true
